apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: node-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-nginx-app
  template:
    metadata:
      labels:
        app: node-nginx-app
    spec:
      containers:
      - name: node-app
        image: mmregistry.mmvietnam.com:5000/node-nginx-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: mmregistry-secret

