apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-nginx-app
  labels:
    app: node-nginx-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-nginx-app
  template:
    metadata:
      labels:
        app: node-nginx-app
    spec:
      containers:
      - name: node-app
        image: node:14
        command: ["node", "index.js"]
        ports:
        - containerPort: 3000
      - name: nginx
        image: nginx:alpine
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

