apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: node-nginx-app
spec:
  selector:
    app: node-nginx-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

